
# Code Book

This code book summarizes the resulting data fields in tidydata.txt.

#Identifiers

Subject - The ID of the test subject
Code - The type of activity performed when the corresponding measurements were taken

#Measurements

 "Subject"
 "Code"
 "TimeBodyAcceleration-mean()-X"
 "TimeBodyAcceleration-mean()-Y"
 "TimeBodyAcceleration-mean()-Z"
 "TimeGravityAcceleration-mean()-X"
 "TimeGravityAcceleration-mean()-Y"
 "TimeGravityAcceleration-mean()-Z"
 "TimeBodyAccelerationJerk-mean()-X"
 "TimeBodyAccelerationJerk-mean()-Y"
 "TimeBodyAccelerationJerk-mean()-Z"
 "TimeBodyGyroscope-mean()-X"
 "TimeBodyGyroscope-mean()-Y"
 "TimeBodyGyroscope-mean()-Z"
 "TimeBodyGyroscopeJerk-mean()-X"
 "TimeBodyGyroscopeJerk-mean()-Y"
 "TimeBodyGyroscopeJerk-mean()-Z"
 "TimeBodyAccelerationMagnitude-mean()"
 "TimeGravityAccelerationMagnitude-mean()"
 "TimeBodyAccelerationJerkMagnitude-mean()"
 "TimeBodyGyroscopeMagnitude-mean()"
 "TimeBodyGyroscopeJerkMagnitude-mean()"
 "FrequencyBodyAcceleration-mean()-X"
 "FrequencyBodyAcceleration-mean()-Y"
 "FrequencyBodyAcceleration-mean()-Z"
 "FrequencyBodyAcceleration-meanFreq()-X"
 "FrequencyBodyAcceleration-meanFreq()-Y"
 "FrequencyBodyAcceleration-meanFreq()-Z"
 "FrequencyBodyAccelerationJerk-mean()-X"
 "FrequencyBodyAccelerationJerk-mean()-Y"
 "FrequencyBodyAccelerationJerk-mean()-Z"
 "FrequencyBodyAccelerationJerk-meanFreq()-X"
 "FrequencyBodyAccelerationJerk-meanFreq()-Y"
 "FrequencyBodyAccelerationJerk-meanFreq()-Z"
 "FrequencyBodyGyroscope-mean()-X"
 "FrequencyBodyGyroscope-mean()-Y"
 "FrequencyBodyGyroscope-mean()-Z"
 "FrequencyBodyGyroscope-meanFreq()-X"
 "FrequencyBodyGyroscope-meanFreq()-Y"
 "FrequencyBodyGyroscope-meanFreq()-Z"
 "FrequencyBodyAccelerationMagnitude-mean()"
 "FrequencyBodyAccelerationMagnitude-meanFreq()"
 "FrequencyBodyBodyAccelerationJerkMagnitude-mean()"
 "FrequencyBodyBodyAccelerationJerkMagnitude-meanFreq()"
 "FrequencyBodyBodyGyroscopeMagnitude-mean()"
 "FrequencyBodyBodyGyroscopeMagnitude-meanFreq()"
 "FrequencyBodyBodyGyroscopeJerkMagnitude-mean()"
 "FrequencyBodyBodyGyroscopeJerkMagnitude-meanFreq()"
 "Angle(tBodyAccelerationMean,Gravity)"
 "Angle(tBodyAccelerationJerkMean),GravityMean)"
 "Angle(tBodyGyroscopeMean,GravityMean)"
 "Angle(tBodyGyroscopeJerkMean,GravityMean)"
 "Angle(X,GravityMean)" "Angle(Y,GravityMean)"
 "Angle(Z,GravityMean)"
 "TimeBodyAcceleration-std()-X"
 "TimeBodyAcceleration-std()-Y"
 "TimeBodyAcceleration-std()-Z"
 "TimeGravityAcceleration-std()-X"
 "TimeGravityAcceleration-std()-Y"
 "TimeGravityAcceleration-std()-Z"
 "TimeBodyAccelerationJerk-std()-X"
 "TimeBodyAccelerationJerk-std()-Y"
 "TimeBodyAccelerationJerk-std()-Z" 
 "TimeBodyGyroscope-std()-X"
 "TimeBodyGyroscope-std()-Y"
 "TimeBodyGyroscope-std()-Z"
 "TimeBodyGyroscopeJerk-std()-X"
 "TimeBodyGyroscopeJerk-std()-Y"
 "TimeBodyGyroscopeJerk-std()-Z"
 "TimeBodyAccelerationMagnitude-std()"
 "TimeGravityAccelerationMagnitude-std()"
 "TimeBodyAccelerationJerkMagnitude-std()"
 "TimeBodyGyroscopeMagnitude-std()"
 "TimeBodyGyroscopeJerkMagnitude-std()"
 "FrequencyBodyAcceleration-std()-X"
 "FrequencyBodyAcceleration-std()-Y"
 "FrequencyBodyAcceleration-std()-Z"
 "FrequencyBodyAccelerationJerk-std()-X"
 "FrequencyBodyAccelerationJerk-std()-Y"
 "FrequencyBodyAccelerationJerk-std()-Z"
 "FrequencyBodyGyroscope-std()-X"
 "FrequencyBodyGyroscope-std()-Y"
 "FrequencyBodyGyroscope-std()-Z"
 "FrequencyBodyAccelerationMagnitude-std()"
 "FrequencyBodyBodyAccelerationJerkMagnitude-std()"
 "FrequencyBodyBodyGyroscopeMagnitude-std()"
 "FrequencyBodyBodyGyroscopeJerkMagnitude-std()"

#Activity Labels

WALKING (value 1): subject was walking during the test
WALKING_UPSTAIRS (value 2): subject was walking up a staircase during the test
WALKING_DOWNSTAIRS (value 3): subject was walking down a staircase during the test
SITTING (value 4): subject was sitting during the test
STANDING (value 5): subject was standing during the test
LAYING (value 6): subject was laying down during the test


